AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "EkiawaseApi"
      StageName: "dev"
      Cors:
        AllowOrigin: "'*'"  # 任意のオリジンを許可
        AllowMethods: "'GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization'"

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: nodejs18.x  
      CodeUri: ../../apps/api/dist
      Events:
        Api:
          Type: Api
          Properties:
            Path: /suggest-midpoint
            Method: get
            RestApiId:
              Ref: ApiGateway  # ここでAPI Gatewayリソースを参照
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Export:
      Name: EkiawaseApiUrl